In [148]:
import datetime

import numpy as np
import pandas as pd

import plotly
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots
from plotly.graph_objs.scatter import Line
from plotly.graph_objs import Scatter

In [149]:
data = np.loadtxt('ex1data2.txt', delimiter=',')
data

array([[2.10400e+03, 3.00000e+00, 3.99900e+05],
       [1.60000e+03, 3.00000e+00, 3.29900e+05],
       [2.40000e+03, 3.00000e+00, 3.69000e+05],
       [1.41600e+03, 2.00000e+00, 2.32000e+05],
       [3.00000e+03, 4.00000e+00, 5.39900e+05],
       [1.98500e+03, 4.00000e+00, 2.99900e+05],
       [1.53400e+03, 3.00000e+00, 3.14900e+05],
       [1.42700e+03, 3.00000e+00, 1.98999e+05],
       [1.38000e+03, 3.00000e+00, 2.12000e+05],
       [1.49400e+03, 3.00000e+00, 2.42500e+05],
       [1.94000e+03, 4.00000e+00, 2.39999e+05],
       [2.00000e+03, 3.00000e+00, 3.47000e+05],
       [1.89000e+03, 3.00000e+00, 3.29999e+05],
       [4.47800e+03, 5.00000e+00, 6.99900e+05],
       [1.26800e+03, 3.00000e+00, 2.59900e+05],
       [2.30000e+03, 4.00000e+00, 4.49900e+05],
       [1.32000e+03, 2.00000e+00, 2.99900e+05],
       [1.23600e+03, 3.00000e+00, 1.99900e+05],
       [2.60900e+03, 4.00000e+00, 4.99998e+05],
       [3.03100e+03, 4.00000e+00, 5.99000e+05],
       [1.76700e+03, 3.00000e+00, 2.5290

In [150]:
X = data[:, [0, 1]]
y = np.array([data[:, 2]]).T
X.shape, y.shape

((47, 2), (47, 1))

In [151]:
def feature_normalize(X):
    mu = np.mean(X, 0)
    sigma = np.std(X, 0)
    X_norm = (X - mu) / sigma
    return X_norm, mu, sigma

In [152]:
XX, mu, sigma = feature_normalize(X)
XX, mu, sigma

(array([[ 1.31415422e-01, -2.26093368e-01],
        [-5.09640698e-01, -2.26093368e-01],
        [ 5.07908699e-01, -2.26093368e-01],
        [-7.43677059e-01, -1.55439190e+00],
        [ 1.27107075e+00,  1.10220517e+00],
        [-1.99450507e-02,  1.10220517e+00],
        [-5.93588523e-01, -2.26093368e-01],
        [-7.29685755e-01, -2.26093368e-01],
        [-7.89466782e-01, -2.26093368e-01],
        [-6.44465993e-01, -2.26093368e-01],
        [-7.71822042e-02,  1.10220517e+00],
        [-8.65999486e-04, -2.26093368e-01],
        [-1.40779041e-01, -2.26093368e-01],
        [ 3.15099326e+00,  2.43050370e+00],
        [-9.31923697e-01, -2.26093368e-01],
        [ 3.80715024e-01,  1.10220517e+00],
        [-8.65782986e-01, -1.55439190e+00],
        [-9.72625673e-01, -2.26093368e-01],
        [ 7.73743478e-01,  1.10220517e+00],
        [ 1.31050078e+00,  1.10220517e+00],
        [-2.97227261e-01, -2.26093368e-01],
        [-1.43322915e-01, -1.55439190e+00],
        [-5.04552951e-01, -2.260

In [153]:
alpha = 0.01
num_iters = 400
theta = np.zeros((3, 1))
theta

array([[0.],
       [0.],
       [0.]])

In [154]:
def h(X, theta):
    return X @ theta

In [155]:
def computeCost(X, y, theta):
    m =  X.shape[0]
    J = 1/(2 * m) * np.sum((h(X, theta) - y) ** 2)
    return J

In [156]:
def gradientDescentMulti(X, y, theta, alpha, num_iters):
    m = X.shape[0]
    theta_out = theta
    J_history = np.zeros(num_iters)
    for i in range(num_iters):
        theta_out -= alpha / m * X.T @ (h(X, theta_out) - y)
        J_history[i] = computeCost(X, y, theta_out)
    return theta_out, J_history


In [157]:
theta = np.zeros((3, 1))
XwithX0 = np.c_[np.ones((XX.shape[0], 1)), XX]
th, J_history = gradientDescentMulti(XwithX0, y, theta, alpha, num_iters)
J_history

array([6.42977763e+10, 6.30310183e+10, 6.17906942e+10, 6.05762369e+10,
       5.93870917e+10, 5.82227165e+10, 5.70825809e+10, 5.59661664e+10,
       5.48729661e+10, 5.38024840e+10, 5.27542352e+10, 5.17277455e+10,
       5.07225512e+10, 4.97381986e+10, 4.87742442e+10, 4.78302542e+10,
       4.69058042e+10, 4.60004793e+10, 4.51138734e+10, 4.42455895e+10,
       4.33952394e+10, 4.25624431e+10, 4.17468290e+10, 4.09480338e+10,
       4.01657018e+10, 3.93994853e+10, 3.86490441e+10, 3.79140452e+10,
       3.71941632e+10, 3.64890795e+10, 3.57984824e+10, 3.51220671e+10,
       3.44595353e+10, 3.38105953e+10, 3.31749615e+10, 3.25523545e+10,
       3.19425011e+10, 3.13451339e+10, 3.07599912e+10, 3.01868171e+10,
       2.96253609e+10, 2.90753776e+10, 2.85366274e+10, 2.80088755e+10,
       2.74918923e+10, 2.69854530e+10, 2.64893378e+10, 2.60033314e+10,
       2.55272232e+10, 2.50608070e+10, 2.46038813e+10, 2.41562485e+10,
       2.37177155e+10, 2.32880932e+10, 2.28671966e+10, 2.24548446e+10,
      

In [158]:
px.scatter(y=J_history)

In [165]:
params = np.array([1650, 3])
params = (params - mu) / sigma
params = np.r_[1, params]
price = params @ th
th, params, price

(array([[334302.06399328],
        [ 99411.44947359],
        [  3267.01285407]]),
 array([ 1.        , -0.44604386, -0.22609337]),
 array([289221.54737122]))

In [186]:
th = np.linalg.pinv(X.T @ X) @ X.T @ y
th, XwithX0, y

(array([89597.90954355,   139.21067402, -8738.01911255]),
 array([[ 1.00000000e+00,  1.31415422e-01, -2.26093368e-01],
        [ 1.00000000e+00, -5.09640698e-01, -2.26093368e-01],
        [ 1.00000000e+00,  5.07908699e-01, -2.26093368e-01],
        [ 1.00000000e+00, -7.43677059e-01, -1.55439190e+00],
        [ 1.00000000e+00,  1.27107075e+00,  1.10220517e+00],
        [ 1.00000000e+00, -1.99450507e-02,  1.10220517e+00],
        [ 1.00000000e+00, -5.93588523e-01, -2.26093368e-01],
        [ 1.00000000e+00, -7.29685755e-01, -2.26093368e-01],
        [ 1.00000000e+00, -7.89466782e-01, -2.26093368e-01],
        [ 1.00000000e+00, -6.44465993e-01, -2.26093368e-01],
        [ 1.00000000e+00, -7.71822042e-02,  1.10220517e+00],
        [ 1.00000000e+00, -8.65999486e-04, -2.26093368e-01],
        [ 1.00000000e+00, -1.40779041e-01, -2.26093368e-01],
        [ 1.00000000e+00,  3.15099326e+00,  2.43050370e+00],
        [ 1.00000000e+00, -9.31923697e-01, -2.26093368e-01],
        [ 1.00000000e+00,  

In [187]:
price = np.array([1, 1650, 3]) @ th
price

293081.4643349717